### ISSUE TITLE
synology_dsm camera enhancement

### ISSUE THREAD

**Issue by S-Przybylski** [hacf-fr/home-assistant-core#34]
## The problem

Dear @Quentame 
Since i noticed that the good woking synology camera integration will be removed in HA 0.118, I investigated the enhanced synology_dsm integration in the current HA 0.116.0.dev. (I already posted this in a feature request, but it seems that the module is used seldomly https://community.home-assistant.io/t/synology-dsm-camera-enhancements/229763. Therefore I try to get in contact with you using that issue)

Behaviour of new synology_dsm integration (camera) in contrast to the deprecated one:
    I found out that the new synology_dsm integration tends to create problems by showing this 8MP streams using HLS (no mjpeg) at all (this seems to be the new default). The delay is worse > 10 sec if its working.
    My Samsung S7 (ha app and browser) and also my older PC which worked well for presenting the lovelace interface up to now often struggle with the fixed 8MP camera streams - see environment.
    I also noticed thats its vital to create an administrative user instead of an surveilance station user.

The old integration used mjpeg for presenting (very fast <= 3 sec delay) with medium stream resolution, which is sufficient for a mounted tablet at all.

Perhaps the current documentation could be enhanced to first mention the capability of the camera enhancement and second to explain how to use the camera stuff of the synology_dsm module (perhaps explain how to create a lovelace object and which options (save picture / save movie is available).

## Environment

- Home Assistant Core release with the issue: 0.116.0.dev
- Last working Home Assistant Core release (if known): -
- Operating environment (OS/Container/Supervised/Core): RASPI 4 4GB Docker ARM from offical project
- Integration causing this issue: synology_dsm
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/synology_dsm/

My configuration:
I personally use 4 x 8MP cameras with three streams connected to the synology NAS 713+. All three streams are configured: One with 8MP, one with 1MP and one as a kind of thumbnail stream.
## Problem-relevant `configuration.yaml`

```
none - configured via integration
```

## Traceback/Error logs

```
none
```

## Additional information
At the end i dream to have an easy to use dashboard for my camera modules:
- fast/low delay stream in terms of an overview for lovelace (i.e. using mid resolution and mjpeg is OK)
- abillity to manually switch to the highest resultion HLS stream for active watching
- save pictures and streams (then with the higest quality)
- navigate through the history (independent if realized using synology nas or HA technology)

I have several ideas to improve that module:

- Create a configuration item to configure the available resolution for streaming in lovelace (perhaps interactively)
- Create a configuration item to configure the available streaming technology HLS or mjpeg for lovelace (perhaps interactively)
- Enable actions to save the stream and also pictures in a pre-defined quality (independend what lovelace presents) either built in lovelace or using Synology NAS methods (I am not aware of).
- History module (perhaps realized using the new HA media capabilities).

What do you think? Do you see any chance to get some ideas into the integration?

**Comment by Quentame** [comment]
Hi !

Thanks for your feedback on testing and great ideas of improvements !!! :bulb:

I love the idea to add the `media_browser` capability to Surveillance Station with an history `media_player`.

The `camera` platform uses RTSP to get the stream from cameras.
[Taking a snapshot](https://www.home-assistant.io/integrations/camera/#service-snapshot) or [record](https://www.home-assistant.io/integrations/camera/#service-record) a camera stream is built in the HA `camera` platorm, so it should work (not tested actually).

I can check the resolution/protocol involed in camera streams, but I don't have an ETA for you since I have multiple integrations to maintain.
@shenxn : Would you like to take a look ?


Thanks a lot.

---

Linked with home-assistant/core#40490 & home-assistant/core#39838

**Comment by shenxn** [comment]
@Quentame I'll look into it but I'm currently working on another integration that needs quick fix. Since there seems to be a lot of problems, I think it is better to move the removing schedule to a latter release. At least we should fix all those problems before removing the old one.

**Comment by Quentame** [comment]
@shenxn 
> Since there seems to be a lot of problems, I think it is better to move the removing schedule to a latter release.


From https://community.home-assistant.io/t/synology-dsm-camera-enhancements/229763 , I see 2 problems:
1. [**issue**] Create a configuration item to configure the available resolution for streaming in lovelace (perhaps interactively)
2. [**issue**] Create a configuration item to configure the available streaming technology HLS or mjpeg for lovelace (perhaps interactively)
3. [**shipped**] Enable actions to save the stream and also pictures in a pre-defined quality (independend what lovelace presents) either built in lovelace or using Synology NAS methods (I am not aware of).
4. [**feature_request**] History module (perhaps realized using the new HA media capabilities).

Have you seen more ?

> I think it is better to move the removing schedule to a latter release. At least we should fix all those problems before removing the old one.

I agree, we can do that.

**Comment by shenxn** [comment]
@Quentame So there is one more. Allow users to add only cameras (no system monitoring sensors) with a non-administrative account.

**Comment by S-Przybylski** [comment]
Dear @shenxn 
dear @Quentame 
I love you passion to work on that! Great!
From my perspective it could be also an idea, if you additionally put the capability of the old integration into the new one (using HLS and medium resolution) as a parallel second stream (for each camera). Then you get rid of the old integration as planned and the new one has a additional feature. If I am not wrong, its a more or less a different API call (but I am not a progammer).

Regarding the user account: It was a remark not more. I personally can live with that!

**Comment by S-Przybylski** [comment]
Dear @shenxn 
dear @Quentame 
today i notice that the synology_dsm integration doesn't provide the status (HA state recording) if the stream is recorded by the Disk station itself. I only see the state idle. Is it possible to enhance your integration too?

**Comment by Quentame** [comment]
> today i notice that the synology_dsm integration doesn't provide the status (HA state recording) if the stream is recorded by the Disk station itself. I only see the state idle. Is it possible to enhance your integration too?

Tested on my side and working.
Be careful of your home mode setting.

**Comment by S-Przybylski** [comment]
I do not use the home mode feature. Its off.

**Comment by Quentame** [comment]
> if the stream is recorded by the Disk station itself

What do you mean with _Disk Station_ ?
Now, when there is the [REC] icon on the _Surveillance Station_ camera, the recording status is well retrieved in HA.

**Comment by S-Przybylski** [comment]
I mean my Synology DS713+
Interesting, I don't see that in the entities provided by synology_dsm integration (is always idle), while the old synology integration presents the correct status.
