### ISSUE TITLE
Add UV unit to UV sensor

### ISSUE THREAD

**Issue by mbo18** [hacf-fr/home-assistant-core#42]
## The problem

UV sensor in Météo France integration does not have a unit. So this sensor can't be displayed as a graph in history for example. I know I could use customize.yaml but with this it will be like other meteo integration and will avoid a customization.

Unit for this sensor is defined in homeassistant.const: UV_INDEX

**Comment by oncleben31** [comment]
This one seems super valid. I think you can already push your PR on the official core repository.
