### ISSUE TITLE
Add several sensors to Météo France integration

### ISSUE THREAD

**Issue by mbo18** [hacf-fr/home-assistant-core#44]
## Context

The meteofrance-api returns a lot of information that is currently not available in the meteo france integration. Some are available but in the weather "part". To get them, one should create template sensors which is not that easy...

## Proposal

I suggest to add nearly all information provided by the API to the metro france integration by adding sensors (disabled by default).
I also suggest to name these sensors according the forecast: current, today, daily:
Sensors for the current forecast should be named as-is. Example: `temperature`, `humidity`, `wind_direction`, `wind_gust`, `condition`, etc.
Sensors for today's forecast and the daily forecast should be named differently (these are examples): 
- for today's forecast: `today_high_temperature`, `today_low_temperature`, `today_uv`, `today_xxxx`, `today_condition`, etc.
- for daily forecast: `daily_high_temperature_1d` (or `high_temperature_1d`?), `daily_high_humidity_1d`, etc.

Here are sensors that I would like to see added:

- Current Forecast:
  - Current condition:  
     - Name: `condition`
     - Path: current_forecast:weather:desc
     - Example: "Très nuageux"
   - Current humidity:
     - Name: `humidity`
     - Path: current_forecast:humidity
     - Example: "90%"
   - Current Wind Gust:
     - Name: `wind_gust`
     - Path: current_forecast:wind:gust
     - Example: 0 km/h
   - Current Wind Direction:
     - Name: `wind_direction`
     - Path: current_forecast:wind:direction
     - Example: 235°
- Today's forecast:
  - Condition:  
     - Name: `today_condition`
     - Path: today_forecast:weather:desc
     - Example: "Très nuageux"
   - Min humidity:
     - Name: `today_low_humidity`
     - Path: today_forecast:humidity:min
     - Example: "70%"
   - Max humidity:
     - Name: `today_high_humidity`
     - Path: today_forecast:humidity:max
     - Example: "90%"
   - Min temperature:
     - Name: `today_low_temperature`
     - Path: today_forecast:T:min
     - Example: "4°"
   - Max temperature:
     - Name: `today_high_temperature`
     - Path: today_forecast:T:max
     - Example: "6°"
   - UV:
     - Name: `today_uv`
     - Path: today_forecast:uv
     - Example: "70%"
   - Precipitation:
     - Name: `today_precipitation`
     - Path: today_forecast:precipitation:24h
     - Example: "0.3mm"
- Daily forecast (for the next 3 or 4 days only?):
  - Condition:  
     - Name: `daily_condition_1d`
     - Path: daily_forecast:weather12H:desc
     - Example: "Très nuageux"
   - Min humidity:
     - Name: `daily_low_humidity_1d`
     - Path: daily_forecast:humidity:min
     - Example: "70%"
   - Max humidity:
     - Name: `daily_high_humidity_1d`
     - Path: daily_forecast:humidity:max
     - Example: "90%"
   - Min temperature:
     - Name: `daily_low_temperature_1d`
     - Path: daily_forecast:T:min
     - Example: "4°"
   - Max temperature:
     - Name: `daily_high_temperature_1d`
     - Path: daily_forecast:T:max
     - Example: "6°"
   - UV:
     - Name: `daily_uv_1d`
     - Path: daily_forecast:uv
     - Example: "70%"
   - Precipitation:
     - Name: `daily_precipitation_1d`
     - Path: daily_forecast:precipitation:24h
     - Example: "0.3mm"

Note that the UV sensor should be renamed `today_uv` instead of `uv` as it is not the current UV index but today's forecast UV index.

Current and today's forecast sensors could be added very easily as only the const.py file needs to be modified (well wind has to be converted to km/h in sensor.py). For daily forecast we will need to do an iteration.

## Consequences

A better metro france integration, with more data. No DB overload if these sensors are disabled by default. I see one breaking change in renaming the UV sensor.

**Comment by oncleben31** [comment]
I'm not sure the naming convention you are suggesting for today and next day forecast is accepted by HA now. @Quentame can you give your point of view ?

An alternative could be adding to current sensor a `forecast`attributes with a table (similar to weather)
My point of view on the sensors:

- Good ideas:
   - dedicated current  and forecast `condition` sensor (in French from météofrance)
   - current `wind_gust` sensor
- Already available:
   - current `humidity`, `wind direction` are in the `weather` entity
   - today and forecast `precipitation`, min/max `temperature` are in the `weather`entity
 
- Why not. Need a second point of view (@Quentame ?)
   - min/max for `humidity` 
   - forecast of `uv` only one value per day. What usage. There are better sources for UV forecast  ? No ?

**Comment by mbo18** [comment]
> I'm not sure the naming convention you are suggesting for today and next day forecast is accepted by HA now. @Quentame can you give your point of view ?
> 
> An alternative could be adding to current sensor a `forecast`attributes with a table (similar to weather)
> My point of view on the sensors:
> 
>     * Good ideas:
>       
>       * dedicated current  and forecast `condition` sensor (in French from météofrance)
>       * current `wind_gust` sensor

Yes please :)
> 
>     * Already available:
>       
>       * current `humidity`, `wind direction` are in the `weather` entity
>       * today and forecast `precipitation`, min/max `temperature` are in the `weather`entity

Ok just find out... So not needed anymore, I will be able to get them with template sensors.
> 
>     * Why not. Need a second point of view (@Quentame ?)
>       
>       * min/max for `humidity`
>       * forecast of `uv` only one value per day. What usage. There are better sources for UV forecast  ? No ?

Understandable. There is OpenUV but an API key (so an account) is required. Could UV been added as an attribut to the weather entity in the forecast part?

**Comment by mbo18** [comment]
Another question for me to understand. Why are pressure, wind_speed and temperature available as sensors? We can find them in the weather entity so its redudant (and so why not adding humidity, wind_direction, etc.?)

**Comment by mbo18** [comment]
I've opened a PR for "good ideas"
https://github.com/home-assistant/core/pull/44150

**Comment by oncleben31** [comment]
> Another question for me to understand. Why are pressure, wind_speed and temperature available as sensors? We can find them in the weather entity so its redudant (and so why not adding humidity, wind_direction, etc.?)

Yes you are right. I will add them in a PR.

For the other I'm not yet sure how to implement. I want to avoid having one entity by day of forecast. I think about having for a given parameter:

- state: for current value
- one attribute for forecast for today
- one attribute with a table with datetime and value for next days forecast.

**Comment by mbo18** [comment]
Currently everything is fine from my point of view: I’ve been able to get attributes from the weather entity with template sensors and my 2 PR have been merge 😄
So with 2021.1.0 I will be able to completely remove Dark Sky. 
Thanks for this awesome integration!!

**Comment by oncleben31** [comment]
And what about my proposition to have forecast info in the attributes of an entity ? More than a dedicated entity for each days of forecast

**Comment by mbo18** [comment]
> And what about my proposition to have forecast info in the attributes of an entity ? More than a dedicated entity for each days of forecast

That's a good question. What will be the easiest way to get attributes when working with template sensors?
One entity per parameter would be fine I think. Something like this:
sensor.paris_condition = current value
sensor.paris_condition.condition_0 = today's forecast
sensor.paris_condition.condition_X = next day's forecast

Adding datetime would complicate things no?

PS: I missed something: UV forecast would be a good addition (only thing missing compared to Dark Sky)
