### ISSUE TITLE
Météo-France : Prévisions Journalières et horaires

### ISSUE THREAD

**Issue by clemalex824** [hacf-fr/home-assistant-core#45]
Beaucoup de personnes après avoir intégrée leur ville, se demandent pourquoi elles ne peuvent pas avoir les 2 prévisions simultanément.
Je n'ai pas trouvé de traces sur le forum, et en voulant poster dans Discord salon DEV\Météo-France, j'ai vu que @oncleben31 pointait ici pour les idées d'évolution.

Du coup,
Peut-on avoir par défaut les prévisions journalières et horaires ? 
En somme, avoir une entité pour chacun des modes (weather.ville_hourly et weather.ville_daily).
Je ne sais pas comment fonctionne l'intégration, mais dans un premier temps, pourquoi ne pas demander le mode au moment de l'intégration ? Et si l'utilisateur veut l'autre mode, il refait une intégration.
(pour ma proposition, il faudrait 'simplement' déplacer la sélection du mode, dans le wizard de l'intégration, et mettre le mode dans l'unique_id)

_je trouve bizarre de ne rien trouver sur le sujet, suis-je passé à côté ?_

**Comment by oncleben31** [comment]
Merci pour l'idée et de tracer la demande ici.
Je sais pas encore comment je vais l'implémenter mais j'aime bien l'idée.

**Comment by djtef** [comment]
J'approuve la demande, c'est ce qui est fait sur l'appli officielle Météo France et je trouve que ça manque. Par contre avoir une prévision heure par heure me paraît extrême

**Comment by dx44** [comment]
Je suis également en accord sur le principe de la double entité.

**Comment by oncleben31** [comment]
Allé je me lance dans la PR.

**Comment by clemalex824** [comment]
> Allé je me lance dans la PR.

Ça y est, tu as trouvé comment l'intégrer 🤔 ?
Et du coup avec tous ces fork.. Tu va la pousser où en premier ? Directement ici puis hacf va la pousser ? Ou directement sur ton depot et tu ca la pousser ? Je suis perdu avec tout ces fork... 😇

**Comment by oncleben31** [comment]
Le seul dépôt à suivre c'est l'officiel. Ce fork est là pour recueillir les développements complexes qui peuvent nécessiter du travail à plusieurs. Nous pouvons ainsi faire des relectures de code entre nous et en français. Mais ce n'ai qu'une étape intermédiaire qui n'a pas vocation à être déployé au public.

**Comment by djtef** [comment]
La logique voudrait que @oncleben31 la push dans son dépôt pour une première révision, puis sur hacf pour que la communauté teste et quand on valide on pousse vers HA

**Comment by oncleben31** [comment]
J'ai des doutes sur la communauté valide. Je ne suis pas sur que beaucoup sache comment importer la modification dans leur HA.
En plus la modif dans ce cas n'est pas très compliqué.

**Comment by clemalex824** [comment]
> J'ai des doutes sur la communauté valide. Je ne suis pas sur que beaucoup sache comment importer la modification dans leur HA.
> En plus la modif dans ce cas n'est pas très compliqué.

Je suis d'accord, si besoin de testeur, il y a le forum pour moi. 
> Le seul dépôt à suivre c'est l'officiel. Ce fork est là pour recueillir les développements complexes qui peuvent nécessiter du travail à plusieurs. Nous pouvons ainsi faire des relectures de code entre nous et en français. Mais ce n'ai qu'une étape intermédiaire qui n'a pas vocation à être déployé au public.

Du coup, c'est ma demande d'évolution qui n'est pas au bon endroit pour moi et qui aurait dû être sur le core officiel.. 
Je suis passé par ici, après avoir lu un post discord, mais comme le dit @oncleben31, c'était pour un travail commun avant de pousser la PR 👍

**Comment by oncleben31** [comment]
> Du coup, c'est ma demande d'évolution qui n'est pas au bon endroit pour moi et qui aurait dû être sur le core officiel

Oui et Non, Ca serait plus simple effectivement, mais le GitHub officiel n'accepte que des issues sur des choses qui marchent pas. Les demandes d'évolutions doivent être sur le forum anglophone.

Avec Quentame nous trouvions plus simple de collecter nos idées ici pour pouvoir les retrouver rapidement.

**Comment by oncleben31** [comment]
Manque la MAJ de la doc et une relecture mais nous y sommes presque:
https://github.com/home-assistant/core/pull/44422
